urls.py
from inspect import getmembers, isclass

from django.urls import include, path, re_path
from django.views.decorators.cache import cache_page
from djgeojson.views import GeoJSONLayerView

from meta.models import Source
from meta.views import AppListView, AssumptionsView
from utils.views import FeedbackView

from stemp_abw.app_settings import MAP_DATA_CACHE_TIMEOUT
from stemp_abw import views

app_name = 'stemp_abw'

# Regular URLs
urlpatterns = [
    # https://docs.djangoproject.com/en/2.2/topics/i18n/\
    # translation/#the-set-language-redirect-view
    path('i18n/', include('django.conf.urls.i18n'), name='set_language'),
    path('contact/', views.ContactView.as_view(),
         name='contact'),
    path('', views.IndexView.as_view(),
         name='index'),
    path('app/', views.MapView.as_view(),
         name='map'),
    path('imprint/', views.ImprintView.as_view(),
         name='imprint'),
    path('privacy_policy/', views.PrivacyPolicyView.as_view(),
         name='privacy_policy'),
    # Source views from WAM with highlighting
    path('sources/', AppListView.as_view(app_name=app_name,
                                         model=Source),
         name='sources'),
    path('assumptions/', AssumptionsView.as_view(app_name=app_name),
         name='assumptions'),
    path('sim_status.data', views.SimulationStatus.as_view(),
         name='sim_status.data'),
    path('result_charts.data', views.ResultChartsData.as_view(),
         name='result_charts.data'),
    path('feedback/', FeedbackView.as_view(app_name=app_name),
         name='feedback')
    ]

# Search detail-view-classes and append to URLs
detail_views = {}
for name, obj in getmembers(views.detail_views):
    if isclass(obj):
        if issubclass(obj, views.detail_views.MasterDetailView):
            if obj.model is not None:
                detail_views[obj.model.name] = obj
urlpatterns.extend(
    path('popup/{}/<int:pk>/'.format(name), dview.as_view(),
         name='{}-detail'.format(name))
    for name, dview in detail_views.items()
)
urlpatterns.extend(
    path('popupjs/{}/<int:pk>/'.format(name), dview.as_view(
        template_name='stemp_abw/popups/js_popup.html'),
         name='{}-js'.format(name))
    for name, dview in detail_views.items()
)

# Search JSON data-view classes and append to URLs
data_views = {}
single_data_views = {}
detail_views_list = {mem[0]: mem[1]
                     for mem in getmembers(views.serial_views, isclass)
                     if mem[1].__module__ == views.serial_views.__name__}
for name, obj in detail_views_list.items():
    if isclass(obj):
        if getattr(obj, 'model', None) is not None:
            # serial data detail view
            if issubclass(obj, views.GeoJSONSingleDatasetLayerView):
                single_data_views[obj.model.name] = obj
            # serial data view
            elif issubclass(obj, GeoJSONLayerView):
                data_views[obj.model.name] = obj
        elif getattr(obj, 'model_name', None) is not None:
            # serial data result view
            if issubclass(obj, views.GeoJSONResultLayerData):
                data_views[obj.model_name] = obj
# Append data-views' URLs
urlpatterns.extend(
    re_path(r'^{}.data/'.format(name),
            cache_page(MAP_DATA_CACHE_TIMEOUT)(sview.as_view()),
            name='{}.data'.format(name))
    for name, sview in data_views.items()
)
# Append serial detail-views' URLs
urlpatterns.extend(
    path('{}.data/<int:pk>/'.format(name),
            cache_page(MAP_DATA_CACHE_TIMEOUT)(sview.as_view()),
            name='{}.data'.format(name))
    for name, sview in single_data_views.items()
)

templates/stemp_abw/base.html
<!doctype html>

{% load static %}

<html class="no-js" lang="de">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StEmp-Tool Anhalt</title>
    {% block header %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'stemp_abw/img/ionicons-2.0.1/css/ionicons.css' %}">
    <link rel="stylesheet" href="{% static 'stemp_abw/foundation/css/app.css' %}">
  </head>

  <body>
    <div class="u-vh--100">
      {% block navigation %}{% include 'stemp_abw/navigation_start.html' %}{% endblock %}
      {% block content %}{% endblock %}
    </div>
    <script src="{% static 'stemp_abw/foundation/js/app.js' %}"></script>
    {% block scripts %}{% endblock %}
  </body>
</html>

templates/stemp_abw/contact.html
{% extends 'stemp_abw/base.html' %}
{% load i18n %}

{% block body-class %}u-vh--100{% endblock %}
{% block grid-y-options %}style="overflow-y: visible;"{% endblock %}

{% block content %}
<div class="grid-x grid-padding-x align-center">
  <div class="cell medium-8 large-6">
    <h1>Kontakt</h1>
    <p style="font-weight: 700">Mascha Richter ({% trans 'Projektleiterin' %})<br>
      <a href="mailto:Mascha.Richter@rl-institut.de">{% trans 'E-Mail' %}</a><br>
      <span style="font-weight: 400">+49 (0)30 1208 434 27</span>
    </p>
    <p style="font-weight: 700">Jonathan Amme ({% trans 'Wissenschaftlicher Mitarbeiter' %})<br>
      <a href="mailto:jonathan.amme@rl-institut.de">{% trans 'E-Mail' %}</a><br>
      <span style="font-weight: 400">+49 (0)30 1208 434 26</span>
    </p>
    <p>
      Reiner Lemoine Institut gGmbH<br>
      Rudower Chaussee 12<br>
      {% trans 'Aufgang D' %}<br>
      12489 Berlin
    </p>
    <p>
      {% trans 'Telefon' %}: +49 (0)30 1208 434 0<br>
      {% trans 'Telefax' %}: +49 (0)30 1208 434 99
    </p>
  </div>
</div>
{% endblock %}

templates/stemp_abw/index.html
{% extends "stemp_abw/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block content %}

      <!-- HERO SECTION START -->
      <main>
        <div class="grid-x">

          <section class="grid-x l-bg-color hp-hero">
            <div class="cell u-text--center">
                <h1 class="hp-hero__header">{% trans 'Regionaler Energiebalancekreis Anhalt-Bitterfeld-Wittenberg' %}</h1>
            </div>
            <div class="cell u-text--center hp-subheader">
                <h2 class="hp-hero__subheader">{% trans 'Szenarien unter dem Aspekt einer abgestimmten Flächennutzung' %}</h2>
            </div>
            <div class="cell u-text--center hp-hero__img">
              <img src="{% static 'stemp_abw/img/Anhalt_map_website.png' %}" alt="{% trans 'Anhalt Karte als Bild' %}">
            </div>
            <div class="cell u-text--center hp-subheader">
              <h1 class="hp-hero__header">Good news!</h1>
              <h2 class="hp-hero__subheader">Der Nachfolger dieses Tools - <b>Digiplan Anhalt</b> - ist verfügbar unter: <a href="https://digiplan.rl-institut.de">digiplan.rl-institut.de</a></h2>
            </div>
            <div class="cell u-text--center hp-hero__btn">
              <a href="{% url 'stemp_abw:map' %}" class="btn btn-cta">
                {% trans 'Zum alten Tool' %}
                <i class ="icon ion-chevron-right icon--small"></i>
              </a>
            </div>
            <div class="cell u-text--center hp-hero__toinfos" id="hp-chevron">
              <a href="#hp-info" class="anchor-text anchor-text--light">
                {% trans 'Neu hier?' %}
                <i class ="icon ion-chevron-down icon--small"></i>
              </a>
            </div>
          </section>

          <section class="grid-x align-center l-bg-color--w hp-info" id="hp-info">
            <div class="cell medium-8 large-6 hp-info__text">
              <p>{% trans 'Ein wichtiger Aspekt zur Erfüllung der Klimaziele für 2050 ist die Partizipation der Bürger und Bürgerinnen. Allerdings erschwert die Komplexität von Energiesystemen und damit verbundenen Fragestellungen den Partizipationsprozess oft erheblich.' %}</p>
              <p>{% trans 'Der Szenarienrechner schafft die Möglichkeit, allen interessierten Anspruchsgruppen ein besseres Verständnis über verschiedene Szenarien des regionalen Energiebalancekreises zu vermitteln und die Auswirkungen von Maßnahmen direkt zu ermitteln. Damit wird die Grundlage für eine ebenbürtige Diskussion geschaffen und eine gemeinsame Planung ermöglicht.' %}</p>
            </div>
          </section>

          <section class="grid-x align-center l-bg-color--light hp-features">
            <div class="cell large-10">
              <div class="grid-x align-center">
                <div class="cell">
                  <h2 class="hp-features__header">{% trans 'Wie kann ein erneuerbares, sektorgekoppeltes Energiesystem für die Region in Zukunft aussehen?' %}</h2>
                </div>
                <div class="cell medium-6 hp-features__card">
                  <h3 class="hp-features__subheader">{% trans 'Partizipation' %}</h3>
                  <p>{% trans 'Regionale Akteure, insbesondere BürgerInnen, sollen ermutigt werden, seriös und real an der Mitgestaltung der Energiewende in ABW teilzunehmen. Durch anschauliches Design und geeignete Moderation werden die komplexen Zusammenhänge erfahr- und diskutierbar.' %}</p>
                </div>
                <div class="cell medium-6 hp-features__card">
                  <h3 class="hp-features__subheader">{% trans 'Effizientere Arbeitsweise' %}</h3>
                  <p>{% trans 'Die regionale Energiewende kann mit besser verhandelten Ergebnissen effizienter vorangetrieben werden. Es wird, in der Gesamtheit, eine bessere Planung und Genehmigung von erneuerbaren Energieanlagen ermöglicht.' %}</p>
                </div>
              </div>
              <div class="grid-x align-center">
                <div class="cell medium-6 hp-features__card">
                  <h3 class="hp-features__subheader">{% trans 'Tieferes Verständnis' %}</h3>
                  <p>{% trans 'Dieses Tool wird nicht nur dabei helfen, die Zusammenhänge zwischen verschiedenen Systemen der Energiewirtschaft, Ökologie und Kulturlandschaft besser zu erklären, auch die Interessen und Werte der regionalen Anspruchsgruppen werden sichtbar gemacht. Das gegenseitige Verständnis wächst - auch und gerade bei unterschiedlichen Meinungen.' %}</p>
                </div>
                <div class="cell medium-6 hp-features__card">
                  <h3 class="hp-features__subheader">{% trans 'Open Science' %}</h3>
                  <p>{% trans 'Daten und Quellcodes werden für alle Interessenten bereitgestellt. Das schafft Transparenz und Überprüfbarkeit. Zudem kann die Umsetzung ähnlicher Tools somit erleichtert werden.' %}</p>
                </div>
              </div>
            </div>
          </section>

          <section class="grid-x align-center l-bg-color--white hp-how">
            <div class="cell large-10">
              <div class="grid-x align-center">
                <div class="cell">
                  <h2 class="hp-how__header">{% trans 'Wie funktioniert das Tool?' %}</h2>
                </div>
              </div>
              <div class="grid-x align-center hp-how__section">
                <div class="cell medium-1 hp-how__text medium-order-2">
                  <div class="hp-how__text-nb">
                    <div>1</div>
                  </div>
                </div>
                <div class="cell medium-4 hp-how__text medium-order-3">
                  <div class="hp-how__text-desc">
                    {% trans 'Verschaffe dir einen Überblick über deine Region' %}
                    <ul>
                      <li>{% trans 'Wieviele Menschen leben in den Gemeinden?' %}</li>
                      <li>{% trans 'Wieviel Strom kommt aus Erneuerbaren Energien?' %}</li>
                      <li>{% trans 'Wieviele Windkraftanlagen stehen in den Gemeinden?' %}</li>
                      <li>{% trans 'Welcher Flächenbelastung entspricht das?' %}</li>
                    </ul>
                  </div>
                </div>
                <div class="cell medium-7 hp-how__img medium-order-1">
                  <img src="{% static 'stemp_abw/img/tool/Region.png' %}" alt="{% trans 'Bild Region' %}">
                </div>
              </div>
              <div class="grid-x align-center hp-how__section">
                <div class="cell medium-1 hp-how__text medium-order-2">
                  <div class="hp-how__text-nb">
                    <div>2</div>
                  </div>
                </div>
                <div class="cell medium-4 hp-how__text medium-order-3">
                  <div class="hp-how__text-desc">
                    {% trans 'Definiere dein eigenes Szenario / Energiesystem' %}
                    <ul>
                      <li>{% trans 'Untersuche das Energiesystem der Region' %}</li>
                      <li>{% trans 'Wähle ein Zubauszenario für Windenergie' %}</li>
                      <li>{% trans 'Variiere den Anteil von Windenergie- Photovoltaik- und Biomasseanlagen oder konventionellen Kraftwerken' %}</li>
                      <li>{% trans 'Passe den Verbrauch der Region an' %}</li>
                    </ul>
                  </div>
                </div>
                <div class="cell medium-7 hp-how__img medium-order-1">
                  <img src="{% static 'stemp_abw/img/tool/Energiesystem.png' %}" alt="{% trans 'Bild Energiesystem' %}">
                </div>
              </div>
              <div class="grid-x align-center hp-how__section">
                <div class="cell medium-1 hp-how__text medium-order-2">
                  <div class="hp-how__text-nb">
                    <div>3</div>
                  </div>
                </div>
                <div class="cell medium-4 hp-how__text medium-order-3">
                  <div class="hp-how__text-desc">
                    {% trans 'Passe Flächen für Windenergie an' %}
                    <ul>
                      <li>{% trans 'Sieh dir vorhandene Vorrangflächen für Windenergie an' %}</li>
                      <li>{% trans 'Sieh dir die Tabuzonen für Windenergie in der Region an' %}</li>
                      <li>{% trans 'Entscheide ob der Mindestabstand zu Siedlungen verändert werden soll, um mehr Windenergieanlagen bauen zu können' %}</li>
                      <li>{% trans 'Entscheide ob Waldgebiete zum Bau von Windenergieanlagen zur Verfügung stehen sollen' %}</li>
                      <li>{% trans 'Beobachte die Auswirkungen in der Karte und auf die mögliche Stromerzeugung des Energiesystems' %}</li>
                    </ul>
                  </div>
                </div>
                <div class="cell medium-7 hp-how__img medium-order-1">
                  <img src="{% static 'stemp_abw/img/tool/Flächen.png' %}" alt="{% trans 'Bild Flächennutzung' %}">
                </div>
              </div>
              <div class="grid-x align-center hp-how__section">
                <div class="cell medium-1 hp-how__text medium-order-2">
                  <div class="hp-how__text-nb">
                    <div>4</div>
                  </div>
                </div>
                <div class="cell medium-4 hp-how__text medium-order-3">
                  <div class="hp-how__text-desc">
                    {% trans 'Vergleiche die Ergebnisse mit dem Status Quo' %}
                    <ul>
                      <li>{% trans 'Wie verändert sich der Anteil Erneuerbarer Energien in den Gemeinden und der Region?' %}</li>
                      <li>{% trans 'Wie viele Windkraftanlagen pro km² kommen hinzu?' %}</li>
                      <li>{% trans 'Wie verändert sich der Im- und Export von Strom?' %}</li>
                    </ul>
                  </div>
                </div>
                <div class="cell medium-7 hp-how__img medium-order-1">
                  <img src="{% static 'stemp_abw/img/tool/Ergebnisse.png' %}" alt="{% trans 'Bild Ergebnisse' %}">
                </div>
              </div>
            </div>
          </section>

          <section class="grid-x align-center l-bg-color--light hp-features">
            <div class="cell large-10">
              <div class="grid-x align-center">
                <div class="cell">
                  <h2 class="hp-features__header">{% trans 'Get involved!' %}</h2>
                </div>
                <div class="cell medium-6 hp-features__card">
                  <h3 class="hp-features__subheader">{% trans 'Dokumentation' %}</h3>
                  <p>{% trans 'Weitere Informationen und Hintergründe finden Sie in unserer Dokumentation auf' %} <a href="https://stemp-abw.readthedocs.io/" target="_blank">ReadTheDocs</a>.</p>
                </div>
                <div class="cell medium-6 hp-features__card">
                  <h3 class="hp-features__subheader">{% trans 'Quellcode' %}</h3>
                  <p>{% trans 'Der Quellcode ist auf' %} <a href="https://github.com/rl-institut/WAM_APP_stemp_abw" target="_blank">GitHub<i class="icon ion-social-github" style="font-size: 1.25rem;"></i></a> {% trans 'unter der Lizenz GNU AGPL v3 frei verfügbar.' %}</p>
                </div>
              </div>
            </div>
          </section>

        </div>
      </main>


      <footer class="footer-hp l-bg-color--w">
        <div class="grid-x">

          <div class="cell footer-hp__logo">
            <ul>
              <li>
                <a href="https://reiner-lemoine-institut.de/" target="_blank" rel="noopener" title="{% trans 'Reiner Lemoine Institut' %}">
                  <img class="footer-hp__logo-rli" src="{% static 'stemp_abw/img/rli_logo.png' %}" alt="{% trans 'Logo Reiner Lemoine Institut' %}">
                </a>
              </li>
              <li>
                <a href="https://www.energieavantgarde.de/" target="_blank" rel="noopener" title="{% trans 'Energieavantgarde Anhalt' %}">
                  <img class="footer-hp__logo-eaa" src="{% static 'stemp_abw/img/EAA_logo.png' %}" alt="{% trans 'Logo Energieavantgarde Anhalt' %}">
                </a>
              </li>
              <li>
                <a href="https://www.energieavantgarde.de/" target="_blank" rel="noopener" title="{% trans 'Kopernikus Projekte' %}">
                  <img class="footer-hp__logo-kopernikus" src="{% static 'stemp_abw/img/Logo_ENavi.png' %}" alt="{% trans 'Logo ENavi' %}">
                </a>
              </li>
              <li>
                <a href="https://www.bmbf.de/" target="_blank" rel="noopener" title="{% trans 'Bundesministerium für Bildung und Forschung' %}">
                  <img class="footer-hp__logo-bmbf" src="{% static 'stemp_abw/img/BMBF_logo.png' %}" alt="Logo BMBF">
                </a>
              </li>
            </ul>
          </div>

          <div class="cell medium-10 medium-offset-1">
            <ul class="u-text--center" id="footer-links">
              <li><a class="anchor-text--dark" href="#">{% trans 'Kontakt' %}</a></li>
              <li><a class="anchor-text--dark" href="#">{% trans 'Impressum' %}</a></li>
              <li><a class="anchor-text--dark" href="#">{% trans 'Datenschutz' %}</a></li>
              <li><a class="anchor-text--dark" href="#">{% trans 'Lizenz' %}</a></li>
              <li class="hide-for-small-only">
                <p class="u-no-margin">&copy; {% trans 'Reiner Lemoine Institut gGmbH' %}</p>
              </li>
            </ul>
          </div>

        </div>
      </footer>
{% endblock %}

templates/stemp_abw/layer_popup_reg_mun.html
<p>{{ obj.gen }}</p>
<ul>
    <li>Einwohner: {{ obj.pop_km2 }} pro km²</li>
</ul>

templates/stemp_abw/navigation_app.html
{% extends "stemp_abw/navigation_base.html" %}
{% load i18n %}

{% block app-version %}
<div class="top-bar-left show-for-large" id="app-version">
  Version {{ app_version }}
</div>
{% endblock %}
{% block map-language-switch-confirm %}
<div class="menu">
  <form id="set-lang-form" action="{% url 'stemp_abw:set_language' %}" method="post">
    {% csrf_token %}
    <input name="next" type="hidden" value="{{ request.path }}"/>
    <select class="dropdown menu-form-dropdown" name="language">
      {% for language in languages %}
        {% get_language_info for language as lang %}
        <option value="{{ language }}" {% if current_language == language %} selected{% endif %}>
          {{ lang.name_local }}
        </option>
      {% endfor %}
    </select>
  </form>
</div>
<div>
  <input data-open="map-language-switch-confirm"  type="submit" class="menu menu-form-button" value="OK">
</div>
{% endblock %}
{% block map-index-confirm_1 %}<li><a data-open="map-index-confirm" class="anchor-text--light" href="#">{% trans 'Startseite' %}</a></li>{% endblock %}
{% block map-index-confirm_2 %}<li><a data-open="map-index-confirm" class="anchor-text--light" href="#">{% trans 'Startseite' %}</a></li>{% endblock %}
{% block map-privacy-policy-confirm %}<li><a id="navbar-privacy-policy" data-open="map-private-policy-confirm" class="anchor-text--light" href="#"> {% trans 'Datenschutz' %}</a></li>{% endblock %}
{% block map-sources-confirm %}<li><a data-open="map-sources-confirm" class="anchor-text--light" href="#"><i class ="icon ion-document-text icon--small"></i> {% trans 'Quellen' %}</a></li>{% endblock %}
{% block map-contact-confirm %}<li><a data-open="map-contact-confirm" class="anchor-text--light" href="#"><i class ="icon ion-chatbubbles icon--small"></i> {% trans 'Kontakt' %}</a></li>{% endblock %}
{% block map-imprint-confirm %}<li><a data-open="map-imprint-confirm" class="anchor-text--light" href="#"><i class ="icon ion-filing icon--small"></i> {% trans 'Impressum' %}</a></li>{% endblock %}

templates/stemp_abw/navigation_base.html
{% load i18n %}
{% load language_tags %}
{% language_store as languages %}
{% get_current_language as current_language %}

      <!-- MAIN NAVIGATION START -->
      <nav>
        <div class="title-bar" id="nav-container" data-responsive-toggle="simple-menu" data-hide-for="medium">
          <button class="menu-icon" type="button" data-toggle></button>
          <div class="title-bar-title">{% trans 'Menü' %}</div>
        </div>

        <div class="top-bar" id="simple-menu">
          <div class="top-bar-left show-for-large">
            <ul class="menu">
              {% block map-index-confirm_1 %}<li><a class="anchor-text--light" href="{% url 'stemp_abw:index' %}">{% trans 'Startseite' %}</a></li>{% endblock %}
            </ul>
          </div>
          {% block app-version %}
          {% endblock %}
          {% block link_to_wam %}
          {% endblock %}
          {% block map-language-switch-confirm %}
          <div class="menu">
            <form id="set-lang-form" action="{% url 'stemp_abw:set_language' %}" method="post">
              {% csrf_token %}
              <input name="next" type="hidden" value="{{ request.path }}"/>
              <select class="dropdown menu-form-dropdown" name="language">
                {% for language in languages %}
                  {% get_language_info for language as lang %}
                  <option value="{{ language }}" {% if current_language == language %} selected{% endif %}>
                    {{ lang.name_local }}
                  </option>
                {% endfor %}
              </select>
            </form>
          </div>
          <div>
            <input data-open="map-language-switch-confirm"  type="submit" class="menu menu-form-button" form="set-lang-form" value="OK">
          </div>
          {% endblock %}
          <div>{{ texts.welcome }}</div>
          <div>{{ texts.outlook }}</div>
          <div class="top-bar-right">
            <ul class="dropdown menu" id="nav-list-vertical" data-dropdown-menu>
              {% block map-privacy-policy-confirm %}<li><a id="navbar-privacy-policy" class="anchor-text--light" href="{% url 'stemp_abw:privacy_policy' %}">{% trans 'Datenschutz' %}</a></li>{% endblock %}
              <li>
                <a class="anchor-text--light" href="#">{% trans 'Menü' %}</a>
                <ul class="menu vertical">
                  {% block map-index-confirm_2 %}<li><a class="anchor-text--light" href="{% url 'stemp_abw:index' %}">Startseite</a></li>{% endblock %}
                  {% block link_to_map %}{% endblock %}
                  {% block map-sources-confirm %}<li><a class="anchor-text--light" href="{% url 'stemp_abw:sources' %}"><i class ="icon ion-document-text icon--small"></i> {% trans 'Quellen' %}</a></li>{% endblock %}
                  <li><a class="anchor-text--light" href="https://stemp-abw.readthedocs.io" target="_blank" rel=”noopener noreferrer”><i class ="icon ion-document icon--small"></i> {% trans 'Dokumentation' %}</a></li>
                  <li><a class="anchor-text--light" href="https://github.com/rl-institut/WAM_APP_stemp_abw" target="_blank" rel=”noopener noreferrer”><i class ="icon ion-social-github icon--small"></i> {% trans 'Quellcode' %}</a></li>
                  <li><a class="anchor-text--light text-primary" href="{% url 'stemp_abw:feedback' %}" target="_blank"><i class ="icon ion-chatbubbles icon--small text-primary"></i> {% trans 'Feedback' %}</a></li>
                  {% block map-contact-confirm %}<li><a class="anchor-text--light" href="{% url 'stemp_abw:contact' %}"><i class ="icon ion-chatbubbles icon--small"></i> {% trans 'Kontakt' %}</a></li>{% endblock %}
                  {% block map-imprint-confirm %}<li><a class="anchor-text--light" href="{% url 'stemp_abw:imprint' %}"><i class ="icon ion-filing icon--small"></i> {% trans 'Impressum' %}</a></li>{% endblock %}
                  <!--<li><a class="anchor-text&#45;&#45;light" href="{% url 'stemp_abw:assumptions' %}">Annahmen</a></li>-->
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- MAIN NAVIGATION END -->

templates/stemp_abw/navigation_start.html
{% extends "stemp_abw/navigation_base.html" %}
{% load i18n %}

{% block link_to_map %}<li><a class="anchor-text--light" href="{% url 'stemp_abw:map' %}">{% trans 'Zum Tool' %}</a></li>{% endblock %}
{% block link_to_wam %}
<div class="top-bar-left show-for-large">
    <a class="anchor-text--light" href="../">{% trans 'Zu den WAM-Seiten des RLI' %}<i class="icon ion-chevron-right icon--small"></i></a>
</div>
{% endblock %}

templates/stemp_abw/result_chart.html
{{visualization|safe}}
{% if visualization.tooltip != '' %}
  <p>{{visualization.tooltip}}</p>
{% endif %}

templates/stemp_abw/session_not_found.html
{% extends "stemp_abw/base.html" %}
{% load i18n %}

{% block content %}

<h1>{% trans 'Deine Sitzung ist abgelaufen' %}</h1>
<h2>{% trans 'Bitte starte eine neue Session' %}</h2>

{% endblock %}